server:
  port: 8080

feign:
  client:
    config:
      default:
        loggerLevel: full

monitoring:
  git:
    repository.path:
  jenkins:
    consoleUrl:
  slack:
    token:
    delivery:
      message: "Jenkins Build Fail"
    channel:
      id:
      name: #developer

logging:
  level:
    com.lzdk.monitoring: debug